version: '3'
services:
  app:
    build: .
    image: wallet_service
    env_file:
      - variables.env
    ports:
      - ${IN_SERVER_PORT}:${OUT_SERVER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:13
    env_file:
      - variables.env
    ports:
      - ${IN_DATASOURCE_PORT}:${OUT_DATASOURCE_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: